name: Build & Publish Docker Image

on:
  push:
    tags:
      - "v*"

env:
  IMAGE_NAME: sindvero/vpauto-creation-controller

jobs:
  controller-unit-tests:
    uses: Sindvero/vpauto-creation-controller/.github/workflows/_unit-test.yaml@main

  docker-buildx:
    runs-on: ubuntu-latest
    needs: controller-unit-tests
    if: success()

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DHUB_USER }}
          password: ${{ secrets.DHUB_GHA_VPAUTO_CREATION_TOKEN }}

      - name: Extract tag version
        id: vars
        run: echo "tag=${GITHUB_REF##*/}" >> "$GITHUB_OUTPUT"

      - name: Build and push multi-arch Docker image
        run: |
          make docker-buildx IMG=${{ env.IMAGE_NAME }}:${{ steps.vars.outputs.tag }}
